### ISSUE TITLE
Unupdated

### ISSUE THREAD

**Issue by Crunch-Munch** [XTINKT-STUDIOS/MunchkinsGameTeam#10]
Can you update the readme.md to show the curse file system. Can you also do a rundown of each class and it methods? _-Supreme Helper Robot_

**Comment by xtinktstudios** [comment]
j4c0b g0tt4 put ALL OF the newest of new files in the drive right b4 we leave and I'll transfer them into GH in my 5th period

**Comment by xtinktstudios** [comment]
Alrighty

**Comment by xtinktstudios** [comment]
Closed

**Comment by Crunch-Munch** [comment]
> > j4c0b g0tt4 put ALL OF the newest of new files in the drive right b4 we leave and I'll transfer them into GH in my 5th period 
> 
> 
> I don't think that's gonna happen today. I'll get him to upload them tommorow before the end of 4th.
> 

The code meister is not in class today. I'll get him to do it tommorow.
